"""empty message

Revision ID: e1957171b17f
Revises: 
Create Date: 2022-02-18 17:32:41.060578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1957171b17f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('users', 'f_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('f_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
